// Generated by sim/simulate.mjs. Do not edit by hand; run `npm run sim -- --write` to regenerate.
export const CAL = {
  "repsToLock": {
    "pick": 18.1,
    "strum": 12.6,
    "barre": 17.7,
    "scale": 16.3,
    "notes": 14.7,
    "lick": 14.5,
    "melody": 14.6,
    "prog": 12.4,
    "write": 16.1,
    "ear": 18.1
  },
  "overhead": 1.42,
  "fudge": 2.23,
  "generated": "2026-09-27",
  "forecastMedianRatio": 1
};
