// Generated by sim/simulate.mjs. Do not edit by hand; run `npm run sim -- --write` to regenerate.
export const CAL = {
  "repsToLock": {
    "pick": 18.2,
    "strum": 12.9,
    "barre": 18.3,
    "scale": 16.9,
    "notes": 14.4,
    "lick": 14.8,
    "melody": 15,
    "prog": 12.7,
    "write": 16.5,
    "ear": 18.3,
    "piece": 18.1,
    "move": 15.5
  },
  "overhead": 1.31,
  "fudge": 2.94,
  "generated": "2026-09-27",
  "forecastMedianRatio": 1
};
