// Generated by sim/simulate.mjs. Do not edit by hand; run `npm run sim -- --write` to regenerate.
export const CAL = {
  "repsToLock": {
    "pick": 18.1,
    "strum": 12.7,
    "barre": 17.7,
    "scale": 16.6,
    "notes": 15,
    "lick": 14.6,
    "melody": 15,
    "prog": 12.2,
    "write": 16.4,
    "ear": 18.3
  },
  "overhead": 1.42,
  "fudge": 2.49,
  "generated": "2026-09-27",
  "forecastMedianRatio": 1
};
